import numpy as np
A = np.ones((1,12))
n = int(input("Введите число: "))
B = np.random.randint(n, n + 12, (1,12))
C = np.random.randint(60, 82, (1,12))
D = np.vstack((A, B, C))
X = D.transpose()
Y = np.random.randint(13.5, 18.6, 12)
XTrans = np.transpose(X)
a = np.linalg.inv(XTrans.dot(X)).dot(XTrans).dot(Y)
print("Оценки уранения регресси: ", a)
Check = X.dot(a)
print("\nПолученные значения:")
print(Check)
print("\nИсходные значения Y:")
print(Y)